format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

right_format = """
$cmd_duration
"""

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[($untracked$modified)]($style) ($ahead_behind$stashed)]($style)"
style = "cyan"
untracked = "[*](red)"
modified = "[*](red)"
staged = ""
conflicted = ""
renamed = ""
deleted = ""
ahead = "[⇡](yellow)"
behind = "[⇣](red)"
diverged = "[⇕](yellow)"
stashed = "≡"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
