
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

right_format = """
$cmd_duration"""

[directory]
style = "#83a598"

[character]
success_symbol = "[❯](#b8bb26)"
error_symbol = "[❯](#fb4934)"
vimcmd_symbol = "[❮](#8ec07c)"

[git_branch]
format = "[$branch]($style)"
style = "#fabd2f"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#fb4934) ($ahead_behind$stashed)]($style)"
style = "#d3869b"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#ebdbb2"

[cmd_duration]
format = "[$duration]($style) "
style = "#d79921"

[python]
format = "[$virtualenv]($style) "
style = "#689d6a"
