#!/usr/bin/env python3
"""Generate the Ember theme family for Zed from palette definitions."""
import json

def a(hex6, alpha=""):
    return hex6 + alpha + ("ff" if not alpha else "")

# hue roles shared across the family; each variant supplies its cuts
DAILY_DARK = dict(
    appearance="dark",
    bg0="#272420", bg1="#2f2b26", bg2="#37322c", sel="#433c32", line="#433c32",
    ed="#2e2a25", ed_line="#38332b",  # editor canvas sits lighter than chrome
    fg="#ddc7a1", muted="#a89984", faint="#928374", disabled="#665c54",
    red="#ea6962", green="#a9b665", yellow="#d8a657", blue="#83a598",
    purple="#d3869b", aqua="#89b482", orange="#e78a4e",
    kw="#bf7a6a", fn="#a9b665", string="#89b482", num="#d3869b", typ="#d8a657",
    comment="#928374",
    term_black="#2e2b27", term_bblack="#665c54",
    term_white="#ddc7a1", term_bwhite="#ecd9b8",
)
DAILY_LIGHT = dict(
    appearance="light",
    bg0="#f7f3ea", bg1="#efeade", bg2="#e9e2d2", sel="#e3dcca", line="#e2dbc9",
    fg="#3c3836", muted="#7c6f64", faint="#928374", disabled="#a89984",
    red="#c14a4a", green="#6c782e", yellow="#b47109", blue="#45707a",
    purple="#945e80", aqua="#4c7a5d", orange="#c35e0a",
    kw="#a0604f", fn="#6c782e", string="#4c7a5d", num="#945e80", typ="#b47109",
    comment="#928374",
    term_black="#3c3836", term_bblack="#665c54",
    term_white="#efeade", term_bwhite="#f7f3ea",
)
WEEKEND_DARK = dict(
    appearance="dark",
    bg0="#131110", bg1="#1a1715", bg2="#221e1a", sel="#2e2921", line="#2a2622",
    fg="#f3e7cd", muted="#a89984", faint="#5f574c", disabled="#4a443c",
    red="#f47a72", green="#99d8ac", yellow="#f2cd8b", blue="#83a598",
    purple="#d3869b", aqua="#89b482", orange="#f2cd8b",
    kw="#a89984", fn="#f2cd8b", string="#d9c1ff", num="#f2cd8b", typ="#f2cd8b",
    comment="#5f574c",
    term_black="#221e1a", term_bblack="#5f574c",
    term_white="#f3e7cd", term_bwhite="#fdf4de",
)
WEEKEND_LIGHT = dict(
    appearance="light",
    bg0="#f6f2ea", bg1="#eee9dd", bg2="#e8e1d2", sel="#e1dac9", line="#e2dbca",
    fg="#221e18", muted="#7c6f64", faint="#a49a89", disabled="#b5ac9c",
    red="#c14a4a", green="#2e7a58", yellow="#96731f", blue="#45707a",
    purple="#945e80", aqua="#4c7a5d", orange="#96731f",
    kw="#7c6f64", fn="#96731f", string="#6f5694", num="#96731f", typ="#96731f",
    comment="#a49a89",
    term_black="#3c3836", term_bblack="#665c54",
    term_white="#eee9dd", term_bwhite="#f6f2ea",
)

def syn(color, style=None, weight=None):
    return {"color": a(color), "font_style": style, "font_weight": weight}

def build(name, p, vesper_grammar=False):
    kw_style = None if vesper_grammar else "italic"
    dark = p["appearance"] == "dark"
    status_bg = a(p["bg0"])
    style = {
        "accents": [a(p["orange"]), a(p["green"]), a(p["yellow"]), a(p["blue"]),
                    a(p["purple"]), a(p["aqua"]), a(p["red"])],
        "border": a(p["line"]),
        "border.variant": p["fg"] + "10",
        "border.focused": p["blue"] + "40",
        "border.selected": p["muted"] + "40",
        "border.transparent": p["fg"] + "08",
        "border.disabled": p["fg"] + "08",
        "elevated_surface.background": a(p["bg1"]),
        "surface.background": a(p["bg1"]),
        "background": a(p["bg0"]),
        "element.background": "#00000000",
        "element.hover": p["fg"] + "10",
        "element.active": p["fg"] + "18",
        "element.selected": p["muted"] + "1c",
        "element.disabled": "#00000000",
        "drop_target.background": p["yellow"] + "30",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": p["fg"] + "10",
        "ghost_element.active": p["fg"] + "18",
        "ghost_element.selected": p["muted"] + "1c",
        "ghost_element.disabled": "#00000000",
        "text": a(p["fg"]),
        "text.muted": a(p["muted"]),
        "text.placeholder": a(p["faint"]),
        "text.disabled": a(p["disabled"]),
        "text.accent": a(p["fn"] if vesper_grammar else p["blue"]),
        "icon": a(p["fg"]),
        "icon.muted": a(p["muted"]),
        "icon.disabled": a(p["disabled"]),
        "icon.placeholder": a(p["faint"]),
        "icon.accent": a(p["fn"] if vesper_grammar else p["blue"]),
        "status_bar.background": status_bg,
        "title_bar.background": status_bg,
        "title_bar.inactive_background": status_bg,
        "toolbar.background": a(p.get("ed", p["bg0"])),
        "tab_bar.background": a(p["bg1"]),
        "tab.inactive_background": a(p["bg1"]),
        "tab.active_background": a(p.get("ed", p["bg0"])),
        "search.match_background": p["yellow"] + "40",
        "search.active_match_background": p["yellow"] + "66",
        "panel.background": a(p["bg1"]),
        "panel.focused_border": a(p["blue"]),
        "pane.focused_border": a(p["blue"]),
        "scrollbar.thumb.active_background": p["muted"] + "66",
        "scrollbar.thumb.hover_background": p["muted"] + "4d",
        "scrollbar.thumb.background": p["muted"] + "33",
        "scrollbar.thumb.border": p["muted"] + "33",
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": p["line"] + "80",
        "editor.foreground": a(p["fg"]),
        "editor.background": a(p.get("ed", p["bg0"])),
        "editor.gutter.background": a(p.get("ed", p["bg0"])),
        "editor.subheader.background": a(p["bg1"]),
        "editor.active_line.background": a(p.get("ed_line", p["bg1"])),
        "editor.highlighted_line.background": a(p.get("ed_line", p["bg1"])),
        "editor.line_number": a(p["disabled"]),
        "editor.active_line_number": a(p["fg"]),
        "editor.hover_line_number": a(p["muted"]),
        "editor.invisible": p["muted"] + "40",
        "editor.wrap_guide": p["fg"] + "0d",
        "editor.active_wrap_guide": p["fg"] + "1a",
        "editor.document_highlight.read_background": p["blue"] + "1a",
        "editor.document_highlight.write_background": p["yellow"] + "26",
        "terminal.background": a(p["bg0"]),
        "terminal.foreground": a(p["fg"]),
        "terminal.bright_foreground": a(p["term_bwhite"]),
        "terminal.dim_foreground": a(p["muted"]),
        "terminal.ansi.black": a(p["term_black"]),
        "terminal.ansi.bright_black": a(p["term_bblack"]),
        "terminal.ansi.dim_black": a(p["term_black"]),
        "terminal.ansi.red": a(p["red"]),
        "terminal.ansi.bright_red": a(p["red"]),
        "terminal.ansi.dim_red": a(p["red"]),
        "terminal.ansi.green": a(p["green"]),
        "terminal.ansi.bright_green": a(p["green"]),
        "terminal.ansi.dim_green": a(p["green"]),
        "terminal.ansi.yellow": a(p["yellow"]),
        "terminal.ansi.bright_yellow": a(p["yellow"]),
        "terminal.ansi.dim_yellow": a(p["yellow"]),
        "terminal.ansi.blue": a(p["blue"]),
        "terminal.ansi.bright_blue": a(p["blue"]),
        "terminal.ansi.dim_blue": a(p["blue"]),
        "terminal.ansi.magenta": a(p["purple"]),
        "terminal.ansi.bright_magenta": a(p["purple"]),
        "terminal.ansi.dim_magenta": a(p["purple"]),
        "terminal.ansi.cyan": a(p["aqua"]),
        "terminal.ansi.bright_cyan": a(p["aqua"]),
        "terminal.ansi.dim_cyan": a(p["aqua"]),
        "terminal.ansi.white": a(p["term_white"]),
        "terminal.ansi.bright_white": a(p["term_bwhite"]),
        "terminal.ansi.dim_white": a(p["muted"]),
        "link_text.hover": a(p["blue"]),
        "version_control.added": a(p["green"]),
        "version_control.modified": a(p["yellow"]),
        "version_control.deleted": a(p["red"]),
        "conflict": a(p["orange"]),
        "conflict.background": p["orange"] + "1a",
        "conflict.border": p["orange"] + "33",
        "created": a(p["green"]),
        "created.background": p["green"] + "1a",
        "created.border": p["green"] + "33",
        "deleted": a(p["red"]),
        "deleted.background": p["red"] + "1a",
        "deleted.border": p["red"] + "33",
        "error": a(p["red"]),
        "error.background": p["red"] + "1a",
        "error.border": p["red"] + "33",
        "hidden": a(p["faint"]),
        "hidden.background": a(p["bg1"]),
        "hidden.border": a(p["line"]),
        "hint": a(p["muted"]),
        "hint.background": p["blue"] + "1a",
        "hint.border": p["blue"] + "33",
        "ignored": a(p["faint"]),
        "ignored.background": a(p["bg1"]),
        "ignored.border": a(p["line"]),
        "info": a(p["blue"]),
        "info.background": p["blue"] + "1a",
        "info.border": p["blue"] + "33",
        "modified": a(p["yellow"]),
        "modified.background": p["yellow"] + "1a",
        "modified.border": p["yellow"] + "33",
        "predictive": a(p["disabled"]),
        "predictive.background": a(p["bg1"]),
        "predictive.border": a(p["line"]),
        "renamed": a(p["blue"]),
        "renamed.background": p["blue"] + "1a",
        "renamed.border": p["blue"] + "33",
        "success": a(p["green"]),
        "success.background": p["green"] + "1a",
        "success.border": p["green"] + "33",
        "unreachable": a(p["faint"]),
        "unreachable.background": a(p["bg1"]),
        "unreachable.border": a(p["line"]),
        "warning": a(p["yellow"]),
        "warning.background": p["yellow"] + "1a",
        "warning.border": p["yellow"] + "33",
        "players": [
            {"cursor": a(c), "background": a(c), "selection": c + "3d"}
            for c in [p["blue"], p["green"], p["yellow"], p["purple"],
                      p["aqua"], p["orange"], p["red"], p["muted"]]
        ],
        "syntax": {
            "attribute": syn(p["kw"]),  # rust #[derive] is metadata, not a type
            "boolean": syn(p["fn"] if vesper_grammar else p["blue"]),
            "comment": syn(p["comment"], "italic"),
            "comment.doc": syn(p["comment"], "italic"),
            "constant": syn(p["fn"] if vesper_grammar else p["blue"]),
            "constructor": syn(p["typ"]),
            "embedded": syn(p["fg"]),
            "emphasis": syn(p["fg"], "italic"),
            "emphasis.strong": syn(p["fg"], None, 700),
            "enum": syn(p["typ"]),
            "function": syn(p["fn"]),
            "function.builtin": syn(p["fn"] if vesper_grammar else p["orange"]),
            "function.definition": syn(p["fn"], None, 700),
            "function.method.definition": syn(p["fn"], None, 700),
            "function.special": syn(p["fn"] if vesper_grammar else p["orange"]),
            "function.special.definition": syn(p["fn"] if vesper_grammar else p["orange"], None, 700),
            "hint": syn(p["muted"]),
            "keyword": syn(p["kw"], kw_style),
            "label": syn(p["orange"]),
            "lifetime": syn(p["kw"], "italic"),
            "link_text": syn(p["blue"], "italic"),
            "link_uri": syn(p["string"]),
            "namespace": syn(p["fg"]),
            "number": syn(p["num"]),
            "operator": syn(p["muted"]),
            "predictive": syn(p["disabled"], "italic"),
            "preproc": syn(p["kw"]),
            "primary": syn(p["fg"]),
            "property": syn(p["fg"] if vesper_grammar else p["blue"]),
            "punctuation": syn(p["muted"]),
            "punctuation.bracket": syn(p["muted"]),
            "punctuation.delimiter": syn(p["muted"]),
            "punctuation.list_marker": syn(p["muted"]),
            "punctuation.markup": syn(p["muted"]),
            "punctuation.special": syn(p["orange"]),
            "selector": syn(p["typ"]),
            "selector.pseudo": syn(p["blue"]),
            "string": syn(p["string"]),
            "string.escape": syn(p["orange"]),
            "string.regex": syn(p["orange"]),
            "string.special": syn(p["orange"]),
            "string.special.symbol": syn(p["fn"] if vesper_grammar else p["blue"]),  # ruby symbols = data-blue, per github
            "tag": syn(p["typ"]),
            "text.literal": syn(p["string"]),
            "title": syn(p["typ"], None, 700),
            "type": syn(p["typ"]),
            "type.interface": syn(p["typ"], "italic"),  # rust traits vs concrete types
            "variable": syn(p["fg"]),
            "variable.parameter": syn(p["fg"], "italic"),
            "variable.special": syn(p["num"]),
            "variant": syn(p["typ"]),
            "diff.plus": syn(p["green"]),
            "diff.minus": syn(p["red"]),
        },
        # normal rests gray; insert = hero/green; visual joins the selection
        # golds (mint on weekend); replace gets heat without stealing error red
        # (weekend replace is the one sanctioned non-error red)
        "vim.yank.background": (p["orange"] if vesper_grammar else p["yellow"]) + "40",
        "vim.normal.background": a(p["muted"]),
        "vim.insert.background": a(p["orange"] if vesper_grammar else p["green"]),
        "vim.visual.background": a(p["string"] if vesper_grammar else p["yellow"]),
        "vim.visual_line.background": a(p["string"] if vesper_grammar else p["yellow"]),
        "vim.visual_block.background": a(p["string"] if vesper_grammar else p["yellow"]),
        "vim.replace.background": a(p["red"] if vesper_grammar else p["orange"]),
        "vim.normal.foreground": a(p["bg0"]),
        "vim.insert.foreground": a(p["bg0"]),
        "vim.visual.foreground": a(p["bg0"]),
        "vim.visual_line.foreground": a(p["bg0"]),
        "vim.visual_block.foreground": a(p["bg0"]),
        "vim.replace.foreground": a(p["bg0"]),
    }
    return {"name": name, "appearance": p["appearance"], "style": style}

family = {
    "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
    "name": "Ember",
    "author": "Sam McClenaghan",
    "themes": [
        build("Ember Daily Dark", DAILY_DARK),
        build("Ember Daily Light", DAILY_LIGHT),
        build("Ember Weekend Dark", WEEKEND_DARK, vesper_grammar=True),
        build("Ember Weekend Light", WEEKEND_LIGHT, vesper_grammar=True),
    ],
}

out = "/Users/sammcclenaghan/.dotfiles/dot-config/zed/themes/ember.json"
with open(out, "w") as f:
    json.dump(family, f, indent=2)
    f.write("\n")
print("wrote", out)
json.load(open(out))
print("valid json,", len(family["themes"]), "themes")


# ---- pi (coding agent TUI) themes: ~/.pi/agent/themes/ ----

def pi_theme(name, p, ladder, vesper_grammar=False):
    accent = p["fn"] if vesper_grammar else p["blue"]
    data = p["fn"] if vesper_grammar else p["blue"]  # constants/symbols family
    vars = {
        "bg": ladder["bg"],
        "panel": ladder["panel"],
        "panelAlt": ladder["panelAlt"],
        "selected": ladder["selected"],
        "border": ladder["border"],
        "accent": accent,
        "kw": p["kw"],
        "fn": p["fn"],
        "str": p["string"],
        "num": p["num"],
        "typ": p["typ"],
        "data": data,
        "green": p["green"],
        "red": p["red"],
        "yellow": p["yellow"],
        "orange": p["orange"],
        "text": p["fg"],
        "muted": p["muted"],
        "dim": p["comment"],
        "toolSuccessBg": ladder["toolSuccessBg"],
        "toolErrorBg": ladder["toolErrorBg"],
    }
    colors = {
        "accent": "accent",
        "border": "border",
        "borderAccent": "accent",
        "borderMuted": "dim",
        "success": "green",
        "error": "red",
        "warning": "yellow",
        "muted": "muted",
        "dim": "dim",
        "text": "",
        "thinkingText": "muted",
        "selectedBg": "selected",
        "userMessageBg": "panel",
        "userMessageText": "",
        "customMessageBg": "panelAlt",
        "customMessageText": "",
        "customMessageLabel": "str",
        "toolPendingBg": "panelAlt",
        "toolSuccessBg": "toolSuccessBg",
        "toolErrorBg": "toolErrorBg",
        "toolTitle": "accent",
        "toolOutput": "muted",
        "mdHeading": "typ",
        "mdLink": "data",
        "mdLinkUrl": "muted",
        "mdCode": "str",
        "mdCodeBlock": "muted",
        "mdCodeBlockBorder": "border",
        "mdQuote": "muted",
        "mdQuoteBorder": "border",
        "mdHr": "border",
        "mdListBullet": "orange",
        "toolDiffAdded": "green",
        "toolDiffRemoved": "red",
        "toolDiffContext": "muted",
        "syntaxComment": "dim",
        "syntaxKeyword": "kw",
        "syntaxFunction": "fn",
        "syntaxVariable": "text",
        "syntaxString": "str",
        "syntaxNumber": "num",
        "syntaxType": "typ",
        "syntaxOperator": "muted",
        "syntaxPunctuation": "muted",
        "thinkingOff": "dim",
        "thinkingMinimal": "border",
        "thinkingLow": "accent",
        "thinkingMedium": "str",
        "thinkingHigh": "num",
        "thinkingXhigh": "red",
        "bashMode": "green",
    }
    return {
        "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
        "name": name,
        "vars": vars,
        "colors": colors,
        "export": {
            "pageBg": ladder["bg"],
            "cardBg": ladder["panel"],
            "infoBg": ladder["panelAlt"],
        },
    }

PI_THEMES = [
    pi_theme("ember-daily-dark", DAILY_DARK, dict(
        bg="#2e2a25", panel="#38332b", panelAlt="#403a30", selected="#463f34",
        border="#564e40", toolSuccessBg="#343527", toolErrorBg="#3f2c29")),
    pi_theme("ember-weekend-dark", WEEKEND_DARK, dict(
        bg="#131110", panel="#1a1715", panelAlt="#221e1a", selected="#2e2921",
        border="#403a31", toolSuccessBg="#1b2019", toolErrorBg="#291b19"),
        vesper_grammar=True),
]

import os
pi_dir = os.path.expanduser("~/.pi/agent/themes")
if os.path.isdir(pi_dir):
    for t in PI_THEMES:
        path = os.path.join(pi_dir, t["name"] + ".json")
        with open(path, "w") as f:
            json.dump(t, f, indent=2)
            f.write("\n")
        json.load(open(path))
        print("wrote", path)
